[project]
name = "a-django-junie-test"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "pytest>=8.3.5",
    "pytest-django>=4.11.1",
]
